### PR TITLE
feat: enable usage in browser by providing font array buffer

### PR DESCRIPTION
**Pull request by LabhanshAgrawal**
Added a function to create the Font object from ArrayBuffer of the font
Adding this to make it possible to use this library in the browser with font data from font access API, see this [comment](https://github.com/xtermjs/xterm.js/issues/958#issuecomment-761813922) in xtermjs/xterm.js#958

### CODE REVIEW

**Comment by LabhanshAgrawal** [comment]
@Tyriar @princjef I'm guessing this should be enough to use this module in browser if we directly call `loadBuffer`. Should I move the imports for `util` and `font-finder` inside the load functions where they are used, using `require`?

**Comment by LabhanshAgrawal** [comment]
@princjef can you please take a look at this and tell if it's ok. This will enable xterm ligatures addon to be used inside browsers compared to being electron only at the moment.

**Comment by princjef** [comment]
Hey @LabhanshAgrawal sorry for the delay. The code looks good. Could you add an entry to the API documentation in the README noting the new `loadBuffer` function?

**Comment by LabhanshAgrawal** [comment]
> Hey @LabhanshAgrawal sorry for the delay. The code looks good. Could you add an entry to the API documentation in the README noting the new `loadBuffer` function?

Done

**Pull request merged**
